# This is a basic workflow to help you get started with Actions

name: Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # bash -c ~/work/Custom-LFS-Action/Custom-LFS-Action/env-prep.sh
      - uses: actions/checkout@v4

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Prepare the environment
        run: |
          chmod +x env-prep.sh
          sudo bash ./env-prep.sh
# Attempts to work around the "not found" until i figure it out
      # Runs a single command using the runners shell
      - name: Download the source code
        run: |
          chmod +x prep-sources.sh
          sudo bash ./prep-sources.sh

      - name: First building attempts
        run: |
          sudo cp chroot-prep.sh /root/
          sudo chown lfs /root/chroot-prep.sh
          sudo chmod +x /root/chroot-prep.sh
          sudo -u lfs ./chroot-prep.sh

      # Runs a set of commands using the runners shell
      - name: Make the base structure
        run: |
          echo placeholder
          echo (tm)
